version: "3"
services:
  quart-app:
    restart: always
    image: quart-app
    build:
      context: .
      dockerfile: quart_app/Dockerfile
    ports:
    - "9000:9000"
    env_file:
    - .env
  quart-nginx:
    image: quart-nginx
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
    - "80:80"
    links:
    - quart-app
    depends_on:
    - quart-app